version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0.0

jobs:
  build:
    docker:
      - image: circleci/node:10.12.0
    steps:
      - checkout
      - run:
          name: Nodejs Version
          command: node --version
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run Build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - build/

  deploy_production:
    docker:
      - image: cimg/python:3.6
    steps:
      - attach_workspace:
          at: .
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: build/
          overwrite: false
          to: "s3://ui.wundery.com"

workflows:
  deploy:
    jobs:
      - build
      - deploy_production:
          requires:
            - build
          filters:
            branches:
              only: master
