version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.16

jobs:
  build:
    docker:
      - image: circleci/node:10.12.0
    steps:
      - checkout
      - run:
          name: Nodejs Version
          command: node --version
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run Build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - build/latest

  deploy_production:
    docker:
      - image: circleci/node:10.12.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Assign bucket URL
          command: |
            APP_VERSION=`node -pe "require('./package.json').version"`
            BUCKET_URL=s3://ui.wundery.com/v${APP_VERSION}
      - aws-s3/copy:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: build/latest
          to: BUCKET_URL # update version number here.

workflows:
  deploy:
    jobs:
      - build
      - deploy_production:
          requires:
            - build
          filters:
            branches:
              only: upgrade-bourbon-to-7.0
